# NEUE DACH URLs für Cookie-Banner Datensammlung (Erweiterung)
# Ziel: Zusätzliche 200+ Cookie-Banner Buttons für BERT-Training
# Strategie: Gleiche Branchen erweitern für mehr Datenvielfalt

NEUE_DACH_URLS = [
    # =============================================================================
    # DEUTSCHLAND - ZUSÄTZLICHE WEBSITES (Hohe Cookie-Banner Wahrscheinlichkeit)
    # =============================================================================
    
    # NEWS & MEDIEN - ERWEITERT
    'https://www.handelsblatt.com',
    'https://www.manager-magazin.de',
    'https://www.capital.de',
    'https://www.wirtschaftswoche.de',
    'https://www.impulse.de',
    'https://www.deutsche-wirtschafts-nachrichten.de',
    'https://www.finanzen.net',
    'https://www.telepolis.de',
    'https://www.news.de',
    'https://www.rtl2.de',
    'https://www.sixx.de',
    'https://www.dmax.de',
    'https://www.sport1.de',
    'https://www.dw.com',
    'https://www.deutsche-welle.de',
    'https://www.phoenix.de',
    'https://www.n24.de',
    'https://www.wn.de',
    'https://www.westfalen-blatt.de',
    'https://www.nw.de',
    'https://www.wa.de',
    'https://www.come-on.de',
    'https://www.kreiszeitung.de',
    'https://www.weser-kurier.de',
    'https://www.haz.de',
    'https://www.neuepresse.de',
    'https://www.goettinger-tageblatt.de',
    'https://www.peace.de',
    'https://www.hna.de',
    'https://www.op-online.de',
    
    # E-COMMERCE & SHOPPING - ERWEITERT
    'https://www.müller.de',
    'https://www.xxxlutz.de',
    'https://www.poco.de',
    'https://www.roller.de',
    'https://www.segmüller.de',
    'https://www.ikea.com',
    'https://www.mömax.de',
    'https://www.xxxlutz.at',
    'https://www.home24.de',
    'https://www.wayfair.de',
    'https://www.made.com',
    'https://www.westwing.de',
    'https://www.fashionette.de',
    'https://www.mytheresa.com',
    'https://www.net-a-porter.com',
    'https://www.farfetch.com',
    'https://www.breuninger.com',
    'https://www.engelhorn.de',
    'https://www.lodenfrey.com',
    'https://www.anson-s.de',
    'https://www.peter-hahn.de',
    'https://www.gerry-weber.com',
    'https://www.esprit.de',
    'https://www.s-oliver.com',
    'https://www.tom-tailor.de',
    'https://www.jack-wolfskin.de',
    'https://www.vaude.com',
    'https://www.mammut.com',
    'https://www.patagonia.com',
    'https://www.northface.com',
    'https://www.columbia.com',
    
    # VERGLEICHSPORTALE & SERVICES - ERWEITERT
    'https://www.toppreise.ch',
    'https://www.preis.de',
    'https://www.kelkoo.de',
    'https://www.shopping.com',
    'https://www.preissuchmaschine.de',
    'https://www.geizhals.at',
    'https://www.geizhals.de',
    'https://www.heise-preisvergleich.de',
    'https://www.testberichte.de',
    'https://www.ciao.de',
    'https://www.dooyoo.de',
    'https://www.yopi.de',
    'https://www.holidayguru.de',
    'https://www.urlaubsguru.de',
    'https://www.urlaubspiraten.de',
    'https://www.reiseschnäppchen.de',
    'https://www.travelzoo.de',
    'https://www.groupon.de',
    'https://www.dailydeal.de',
    'https://www.gutscheine.de',
    'https://www.gutscheinpony.de',
    'https://www.sparwelt.de',
    'https://www.mydealz.de',
    'https://www.dealabs.com',
    'https://www.pepper.com',
    
    # IMMOBILIEN & AUTOMOBIL - ERWEITERT
    'https://www.wohnungsboerse.net',
    'https://www.immobilo.de',
    'https://www.homeday.de',
    'https://www.ohne-makler.net',
    'https://www.mcmakler.de',
    'https://www.zoomsquare.com',
    'https://www.nestpick.com',
    'https://www.studenten-wg.de',
    'https://www.wg-gesucht.de',
    'https://www.zwischenmiete.de',
    'https://www.mrporter.com',
    'https://www.autohero.de',
    'https://www.wirkaufendeinauto.de',
    'https://www.auto1.com',
    'https://www.carmundu.de',
    'https://www.heycar.de',
    'https://www.autovista24.de',
    'https://www.adac-shop.de',
    'https://www.dac.de',
    'https://www.avd.de',
    
    # KLEINANZEIGEN & MARKTPLÄTZE - ERWEITERT
    'https://www.hood.de',
    'https://www.ricardo.de',
    'https://www.mercateo.com',
    'https://www.restposten.de',
    'https://www.auktionshaus-felzmann.de',
    'https://www.catawiki.de',
    'https://www.lot-tissimo.com',
    'https://www.auvito.de',
    'https://www.kijiji.de',
    'https://www.locanto.de',
    'https://www.findix.de',
    'https://www.gratisanzeiger.de',
    'https://www.regional.de',
    'https://www.ahano.de',
    'https://www.1a-stellenmarkt.de',
    
    # SOCIAL & COMMUNITY - ERWEITERT
    'https://www.absolventa.de',
    'https://www.graduateland.com',
    'https://www.academics.de',
    'https://www.wissenschaft.de',
    'https://www.hochschulstart.de',
    'https://www.studis-online.de',
    'https://www.studentenwerk.de',
    'https://www.studenten-presse.com',
    'https://www.unicum.de',
    'https://www.pointer.de',
    'https://www.e-fellows.net',
    'https://www.mystipendium.de',
    'https://www.arbeitsagentur.de',
    'https://www.jobcenter.digital',
    'https://www.für-gründer.de',
    'https://www.startup-monitor.de',
    'https://www.deutsche-startups.de',
    'https://www.berlin-startup-jobs.com',
    'https://www.gründerszene.de',
    'https://www.venture-capital-magazin.de',
    
    # TECH & IT - ERWEITERT
    'https://www.it-business.de',
    'https://www.computerwoche.de',
    'https://www.cio.de',
    'https://www.channelpartner.de',
    'https://www.silicon.de',
    'https://www.zdnet.de',
    'https://www.techstage.de',
    'https://www.notebookcheck.com',
    'https://www.notebookjournal.de',
    'https://www.hardwareluxx.de',
    'https://www.computerbase.de',
    'https://www.pcgameshardware.de',
    'https://www.gamestar.de',
    'https://www.gamepro.de',
    'https://www.4players.de',
    'https://www.buffed.de',
    'https://www.mmorpg.de',
    'https://www.spieletipps.de',
    'https://www.mobafire.com',
    'https://www.readmore.de',
    'https://www.androidpit.de',
    'https://www.curved.de',
    'https://www.inside-handy.de',
    'https://www.handy.de',
    'https://www.teltarif.de',
    'https://www.connect.de',
    
    # LIFESTYLE & ENTERTAINMENT - ERWEITERT
    'https://www.eatsmarter.de',
    'https://www.küchengötter.de',
    'https://www.rewe-rezepte.de',
    'https://www.edeka-rezepte.de',
    'https://www.ichkoche.at',
    'https://www.gutekueche.at',
    'https://www.marmiton.org',
    'https://www.750g.com',
    'https://www.cosmopolitan.de',
    'https://www.glamour.de',
    'https://www.instyle.de',
    'https://www.myself.de',
    'https://www.emotion.de',
    'https://www.joy.de',
    'https://www.frauenzimmer.de',
    'https://www.wunderweib.de',
    'https://www.lisa.de',
    'https://www.freundin.de',
    'https://www.für-sie.de',
    'https://www.petra.de',
    'https://www.tina-woman.de',
    'https://www.ok-magazin.de',
    'https://www.closer.de',
    'https://www.intouch.de',
    'https://www.grazia-magazin.de',
    'https://www.harpersbazaar.de',
    'https://www.marieclaire.de',
    
    # GESUNDHEIT & MEDIZIN - ERWEITERT
    'https://www.gesundheit.de',
    'https://www.lifeline.de',
    'https://www.ellviva.de',
    'https://www.vitanet.de',
    'https://www.medizinfo.de',
    'https://www.gesundheitsinformation.de',
    'https://www.krebsinformationsdienst.de',
    'https://www.diabetiker-bund.de',
    'https://www.herzstiftung.de',
    'https://www.lungenliga.ch',
    'https://www.rki.de',
    'https://www.pei.de',
    'https://www.bfarm.de',
    'https://www.iqwig.de',
    'https://www.g-ba.de',
    'https://www.aponet.de',
    'https://www.apotheke-adhoc.de',
    'https://www.pharmazeutische-zeitung.de',
    'https://www.deutsche-apotheker-zeitung.de',
    'https://www.sanicare.de',
    'https://www.medpex.de',
    'https://www.zur-rose.de',
    'https://www.medikamente-per-klick.de',
    'https://www.apotal.de',
    'https://www.mycare.de',
    'https://www.eurapon.de',
    
    # FINANZEN & BANKING - ERWEITERT
    'https://www.postbank.de',
    'https://www.sparda-bank.de',
    'https://www.psd-bank.de',
    'https://www.gls.de',
    'https://www.ethikbank.de',
    'https://www.umweltbank.de',
    'https://www.tomorrow.one',
    'https://www.revolut.com',
    'https://www.wise.com',
    'https://www.monese.com',
    'https://www.number26.de',
    'https://www.cash.ch',
    'https://www.handelszeitung.ch',
    'https://www.finanz-und-wirtschaft.ch',
    'https://www.trend.at',
    'https://www.format.at',
    'https://www.gewinn.com',
    'https://www.fonds-professionell.at',
    'https://www.fondsweb.com',
    'https://www.morningstar.de',
    'https://www.justetf.com',
    'https://www.extra-funds.de',
    'https://www.fondsdiscount.de',
    'https://www.maxblue.de',
    'https://www.flatex.de',
    'https://www.onvista-bank.de',
    'https://www.lynx.de',
    'https://www.captrader.com',
    'https://www.degiro.de',
    'https://www.trade-republic.com',
    'https://www.scalable.capital',
    'https://www.bitpanda.com',
    'https://www.coinbase.com',
    
    # TELEKOMMUNIKATION & UTILITIES - ERWEITERT
    'https://www.congstar.de',
    'https://www.blau.de',
    'https://www.smartmobil.de',
    'https://www.winSIM.de',
    'https://www.premiumsim.de',
    'https://www.simply.de',
    'https://www.discoplus.de',
    'https://www.mobilcom-debitel.de',
    'https://www.otelo.de',
    'https://www.klarmobil.de',
    'https://www.yourfone.de',
    'https://www.crash-tarife.de',
    'https://www.handyvertrag.de',
    'https://www.logitel.de',
    'https://www.preisvergleich-tarife.de',
    'https://www.billiger-telefonieren.de',
    'https://www.wechselpilot.com',
    'https://www.stromvergleich.de',
    'https://www.gasvergleich.de',
    'https://www.e-wie-einfach.de',
    'https://www.vattenfall.de',
    'https://www.eon.de',
    'https://www.rwe.com',
    'https://www.entega.de',
    'https://www.naturstrom.de',
    'https://www.ökostrom.de',
    'https://www.polarstern-energie.de',
    'https://www.lichtblick.de',
    
    # WETTER & LOKALES - ERWEITERT
    'https://www.unwetter.de',
    'https://www.dwd.de',
    'https://www.meteomedia.de',
    'https://www.regenradar.de',
    'https://www.niederschlagsradar.de',
    'https://www.meteogroup.com',
    'https://www.zamg.ac.at',
    'https://www.meteoschweiz.ch',
    'https://www.srf-meteo.ch',
    'https://www.wetter-alarm.at',
    'https://www.ubimet.com',
    'https://www.bergfex.at',
    'https://www.bergfex.ch',
    'https://www.skiinfo.de',
    'https://www.schneehöhen.de',
    'https://www.lawinen.at',
    'https://www.slf.ch',
    
    # TRANSPORT & MOBILITY - ERWEITERT
    'https://www.bvg.de',
    'https://www.vgn.de',
    'https://www.mvv-muenchen.de',
    'https://www.vrr.de',
    'https://www.vrs.de',
    'https://www.vbb.de',
    'https://www.wienerlinien.at',
    'https://www.sbb.ch',
    'https://www.postbus.at',
    'https://www.postbus.ch',
    'https://www.meinferienbus.de',
    'https://www.fernbus.de',
    'https://www.berlinlinienbus.de',
    'https://www.eurolines.de',
    'https://www.ouibus.com',
    'https://www.flix.com',
    'https://www.blablacar.de',
    'https://www.mitfahrgelegenheit.de',
    'https://www.drive2day.de',
    'https://www.car2go.com',
    'https://www.drivenow.com',
    'https://www.sharenow.com',
    'https://www.miles-mobility.com',
    'https://www.cambio-carsharing.de',
    'https://www.stadtmobil.de',
    'https://www.flinkster.de',
    'https://www.sixt.de',
    'https://www.europcar.de',
    'https://www.hertz.de',
    'https://www.avis.de',
    'https://www.enterprise.de',
    'https://www.buchbinder.de',
    'https://www.starcar.de',
    
    # SPORT - ERWEITERT
    'https://www.sport.de',
    'https://www.laola1.tv',
    'https://www.goal.com',
    'https://www.fussballfieber.de',
    'https://www.reviersport.de',
    'https://www.ruhrnachrichten.de',
    'https://www.wa.de',
    'https://www.ruhr24.de',
    'https://www.motorsport-total.com',
    'https://www.auto-motor-und-sport.de',
    'https://www.motorsport-magazin.com',
    'https://www.speedweek.com',
    'https://www.tennis.de',
    'https://www.tennis-point.de',
    'https://www.golf.de',
    'https://www.golfpost.de',
    'https://www.golf-royal.de',
    'https://www.wintersport.de',
    'https://www.ski-online.de',
    'https://www.snowboard.de',
    'https://www.snowtrex.de',
    'https://www.snowplaza.de',
    'https://www.skiresort.de',
    'https://www.liftverbund.at',
    'https://www.skiwelt.at',
    'https://www.kitzsteinhorn.at',
    
    # =============================================================================
    # ÖSTERREICH - ZUSÄTZLICHE .AT DOMAINS
    # =============================================================================
    
    # ZUSÄTZLICHE ÖSTERREICHISCHE NEWS & MEDIEN
    'https://www.profil.at',
    'https://www.news.at',
    'https://www.woman.at',
    'https://www.falter.at',
    'https://www.wienerzeitung.at',
    'https://www.krone.at',
    'https://www.oe24.at',
    'https://www.österreich.at',
    'https://www.weekend.at',
    'https://www.look.at',
    'https://www.miss.at',
    'https://www.madonna.at',
    'https://www.tv-media.at',
    'https://www.servustv.com',
    'https://www.puls4.com',
    'https://www.atv.at',
    'https://www.puls24.at',
    'https://www.okto.tv',
    
    # ZUSÄTZLICHE ÖSTERREICHISCHE SERVICES
    'https://www.findmycar.at',
    'https://www.motor.at',
    'https://www.autorevue.at',
    'https://www.autohaus24.at',
    'https://www.flohmarkt.at',
    'https://www.bazos.at',
    'https://www.laendleanzeiger.at',
    'https://www.regionaut.at',
    'https://www.bekanntschaften.at',
    'https://www.parship.at',
    'https://www.elitepartner.at',
    'https://www.lovescout24.at',
    'https://www.bildkontakte.at',
    'https://www.50plus-treff.at',
    'https://www.christliche-partnersuche.at',
    
    # ZUSÄTZLICHE ÖSTERREICHISCHE UNTERNEHMEN
    'https://www.maximarkt.at',
    'https://www.penny.at',
    'https://www.nah-und-frisch.at',
    'https://www.adeg.at',
    'https://www.sutterlüty.at',
    'https://www.mpreis.at',
    'https://www.unimarkt.at',
    'https://www.zielpunkt.at',
    'https://www.kastner.at',
    'https://www.transgourmet.at',
    'https://www.metro.at',
    'https://www.kika.at',
    'https://www.leiner.at',
    'https://www.möbelix.at',
    'https://www.lagerhaus.at',
    'https://www.baumax.at',
    'https://www.bauhaus.at',
    'https://www.obi.at',
    'https://www.hornbach.at',
    
    # =============================================================================
    # SCHWEIZ - ZUSÄTZLICHE .CH DOMAINS  
    # =============================================================================
    
    # ZUSÄTZLICHE SCHWEIZER NEWS & MEDIEN
    'https://www.handelszeitung.ch',
    'https://www.bilanz.ch',
    'https://www.finanz-und-wirtschaft.ch',
    'https://www.cash.ch',
    'https://www.moneycab.com',
    'https://www.inside-it.ch',
    'https://www.inside-channels.ch',
    'https://www.computerworld.ch',
    'https://www.netzwoche.ch',
    'https://www.itmagazine.ch',
    'https://www.swiss-it-magazin.ch',
    'https://www.startupticker.ch',
    'https://www.schweizer-illustrierte.ch',
    'https://www.annabelle.ch',
    'https://www.femina.ch',
    'https://www.bolero.ch',
    'https://www.presseportal.ch',
    'https://www.newsaktuell.ch',
    'https://www.limmattaler-zeitung.ch',
    'https://www.bzbasel.ch',
    
    # ZUSÄTZLICHE SCHWEIZER SERVICES & E-COMMERCE
    'https://www.toppreise.ch',
    'https://www.preisvergleich.ch',
    'https://www.shoppydeals.ch',
    'https://www.qoqa.ch',
    'https://www.siroop.ch',
    'https://www.brack.ch',
    'https://www.microspot.ch',
    'https://www.fust.ch',
    'https://www.steg-electronics.ch',
    'https://www.melectronics.ch',
    'https://www.mediamarkt.ch',
    'https://www.saturn.ch',
    'https://www.conrad.ch',
    'https://www.digitec.ch',
    'https://www.alternate.ch',
    'https://www.pc-ostschweiz.ch',
    'https://www.steg-computer.ch',
    'https://www.cyberport.ch',
    'https://www.notebooksbilliger.ch',
    'https://www.computeruniverse.ch',
    
    # ZUSÄTZLICHE SCHWEIZER UNTERNEHMEN
    'https://www.denner.ch',
    'https://www.volg.ch',
    'https://www.spar.ch',
    'https://www.otto-s.ch',
    'https://www.vögele.ch',
    'https://www.c-and-a.ch',
    'https://www.h-m.ch',
    'https://www.zara.ch',
    'https://www.zalando.ch',
    'https://www.aboutyou.ch',
    'https://www.fashionette.ch',
    'https://www.manor.ch',
    'https://www.globus.ch',
    'https://www.jelmoli.ch',
    'https://www.loeb.ch',
    'https://www.pfister.ch',
    'https://www.livique.ch',
    'https://www.interio.ch',
    'https://www.conforama.ch',
    'https://www.lipo.ch',
]

# Zusätzliche internationale URLs mit DACH-Fokus
NEUE_COOKIE_HEAVY_URLS = [
    # Weitere internationale Websites mit komplexen Cookie-Bannern
    'https://www.amazon.ch',
    'https://www.amazon.at',
    'https://www.netflix.com',
    'https://www.disney.com',
    'https://www.hulu.com',
    'https://www.prime-video.com',
    'https://www.sky.de',
    'https://www.sky.at',
    'https://www.sky.ch',
    'https://www.joyn.de',
    'https://www.tvnow.de',
    'https://www.zattoo.com',
    'https://www.waipu.tv',
    'https://www.magenta-tv.de',
    'https://www.unitymedia.de',
    'https://www.pyur.com',
    'https://www.tele-columbus.com',
    'https://www.ewe.de',
    'https://www.netcologne.de',
    'https://www.mnet.de'
]

# Kombinierte neue Liste
ALLE_NEUEN_URLS = NEUE_DACH_URLS + NEUE_COOKIE_HEAVY_URLS

print(f"📊 NEUE DACH URLs Statistik:")
print(f"   Neue Deutsche URLs: {len([url for url in NEUE_DACH_URLS if '.de' in url])}")
print(f"   Neue Österreichische URLs: {len([url for url in NEUE_DACH_URLS if '.at' in url])}")  
print(f"   Neue Schweizer URLs: {len([url for url in NEUE_DACH_URLS if '.ch' in url])}")
print(f"   Neue Cookie-Heavy URLs: {len(NEUE_COOKIE_HEAVY_URLS)}")
print(f"   NEUE GESAMT: {len(ALLE_NEUEN_URLS)} URLs")
print(f"\n🎯 Erwartete zusätzliche Cookie-Banner: ~70-80% Success-Rate = {int(len(ALLE_NEUEN_URLS) * 0.75)} Banner")
print(f"🎯 Erwartete zusätzliche Buttons: ~3-5 Buttons/Banner = {int(len(ALLE_NEUEN_URLS) * 0.75 * 4)} Buttons")
print(f"\n✅ Das sind zusätzliche ~{int(len(ALLE_NEUEN_URLS) * 0.75 * 4)} Buttons zu Ihrer bestehenden Liste!")